### PR TITLE
Fix depwarn on 0.5

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by jiahao** [comment]
Any idea what this Travis failure message means?

```
LoadError: ccall: could not find function jl_read_sonames
while loading /home/travis/.julia/v0.5/GSL/deps/build.jl, in expression starting on line 30
```

https://travis-ci.org/jiahao/GSL.jl/jobs/130155601#L531-L532

**Comment by yuyichao** [comment]
It's also happening on master and should be fixed by https://github.com/JuliaLang/julia/pull/16361

**Comment by yuyichao** [comment]
I don't understand why the codecov comment is posted before the CI finishes.....

Anyway, there's a nightly with the BinDeps fix included, forced pushed to restart the CI and not all CI's are passing.

**Comment by yuyichao** [comment]
ping

**Pull request merged**
